comment: false

codecov:
  token: 5c23417d-d65d-4325-8f4b-dc30ef92e77e

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
